name: Auto update

on: workflow_dispatch

jobs:
  prevalence:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repo (with full history)
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    
    - uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.BOT_PRIVATE_KEY }}
        app-id: ${{ secrets.BOT_APP_ID }}
      
    - name: Do the file edits
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
      run: |
        #git config --global user.name "Repo Automation[bot]"
        #git config --global user.email "123456789+repo-automation[bot]@users.noreply.github.com"
        git rm database/domains.json
        git commit -m "Updating domains.json"
        git push
